data_config: 
  train_list: ../face/train_list_face_new.txt
  train_data_path: /misc/scratch11/Voxceleb1_Data/Voxceleb1_Data/Insightface_Aligned_Images/ 
  eval_list: ../face/val_list_face_new.txt 
  eval_data_path: /misc/scratch11/Voxceleb1_Data/Voxceleb1_Data/Insightface_Aligned_Images/
  musan_path: /misc/scratch02/reco/Corpora/VoxCeleb_August2021/musan_split/
  rir_path: /misc/scratch02/reco/Corpora/VoxCeleb_August2021/RIRS_NOISES/simulated_rirs/
  num_eval_frames: 5
  data_loader_workers: 4
  frame_len: 100
  truncate: 0.05
  batch_size: 100

model_config:
  initial_model_a: ../speaker/exps/debug/model_a/model_0199.model
  initial_model_v: ../face/exps/debug/model_v/model_0094.model
  model_a: ecapa1024
  model_v: res18

loss_config:
  margin_v: 0.4
  margin_a: 0.2
  scale_a: 30
  scale_v: 64
  n_class: 1150

trainer_config:
  max_epochs: 200
  grad_norm_clip: 1.0
  snapshot_path: exps/debug/snapshot/snapshot.pt
  save_every: 3
  score_file: exps/debug/score.txt
  eval_trials: ../../veri_val_face.txt 

optimizer_config:
  weight_decay: 2e-5
  learning_rate: 0.001
  learning_rate_decay: 0.65
  lr_decay_start: 5
  lr_decay_every: 2
  lr_decay_rate: 0.8

hydra:
  run:
    dir: ./
